repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: flake8
        name: Flake8
        description: Runs flake8 including extensions
        entry: poetry run flake8
        language: system
        types: [python]
        require_serial: true
