[oauth]
client_id = "CLIENT_ID"
client_secret = "CLIENT_SECRET"
redirect_uri = "REDIRECT_URI"
scope = "SCOPE"

[cache]
auth_cache = "CACHE"

[style]
box_color = "green"
box_style = "SIMPLE_HEAD"
lhs_style = "blue bold"
rhs_style = "white not bold"
